version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: ffmt/docs/source/conf.py   # <-- ajusta si tu conf.py está en otro sitio

python:
  install:
    - pip:
        - sphinx
        - myst-parser
        - sphinx-copybutton
        - sphinx-design
        - sphinx-rtd-theme

formats:
  - htmlzip
  - pdf
