version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: docs/requirements.txt

# Opcional: formatos adicionales además del HTML por defecto
formats:
  - pdf
  - epub
  - htmlzip
