version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: ffmt/docs/source/conf.py   # <-- OJO, con "ffmt/" al inicio

python:
  install:
    - requirements: ffmt/docs/requirements.txt  # <-- también con "ffmt/"

formats:
  - pdf
  - htmlzip
